p8105_hw2_jc5929
================
2022-10-04

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(dplyr)
library(knitr)
  nyc_transit=read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>%
  janitor::clean_names() %>%
  select(line,station_name,station_latitude,
         station_longitude,route1:route11,
         entry,vending,entrance_type,ada) %>%
  mutate(entry=recode(entry,'YES'='TRUE','NO'='FALSE'))
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
nrow(nyc_transit)
ncol(nyc_transit)
```

This dataset contains variables: line, station name, station latitude,
station longitude, and the routes number from route1 to route11, the
entry, vending, entrance type, and also ADA compliance. It has 1868
rows, and 19 columns.

I used the function *clean_names* from the package *janitor* to clean
the variables names in the dataset. This step includes formatting the
characters from upper case letters into lower case letters, and also
added underlines. Next, I used the *select* function to select the
specific columns that I want. And then used the *mutate* function to
change the entry variable from characrer to logical variables.

``` r
dis=distinct(nyc_transit,line,station_name,.keep_all=TRUE)
nrow(dis)
```

    ## [1] 465

``` r
dis %>%
  filter(ada=='TRUE')
```

    ## # A tibble: 84 × 19
    ##    line        stati…¹ stati…² stati…³ route1 route2 route3 route4 route5 route6
    ##    <chr>       <chr>     <dbl>   <dbl> <chr>  <chr>  <chr>  <chr>  <chr>  <chr> 
    ##  1 4 Avenue    Atlant…    40.7   -74.0 B      Q      D      N      R      2     
    ##  2 4 Avenue    DeKalb…    40.7   -74.0 B      Q      R      <NA>   <NA>   <NA>  
    ##  3 4 Avenue    Pacifi…    40.7   -74.0 B      Q      D      N      R      2     
    ##  4 42nd St Sh… Grand …    40.8   -74.0 GS     4      5      6      7      <NA>  
    ##  5 6 Avenue    34th St    40.7   -74.0 B      D      F      M      N      Q     
    ##  6 6 Avenue    47-50t…    40.8   -74.0 B      D      F      M      <NA>   <NA>  
    ##  7 6 Avenue    Church…    40.6   -74.0 F      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  8 63rd Street 21st St    40.8   -73.9 F      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  9 63rd Street Lexing…    40.8   -74.0 F      <NA>   <NA>   <NA>   <NA>   <NA>  
    ## 10 63rd Street Roosev…    40.8   -74.0 F      <NA>   <NA>   <NA>   <NA>   <NA>  
    ## # … with 74 more rows, 9 more variables: route7 <chr>, route8 <dbl>,
    ## #   route9 <dbl>, route10 <dbl>, route11 <dbl>, entry <chr>, vending <chr>,
    ## #   entrance_type <chr>, ada <lgl>, and abbreviated variable names
    ## #   ¹​station_name, ²​station_latitude, ³​station_longitude

``` r
dis %>%
  filter(vending=='NO')%>%
  filter(entry=='TRUE')
```

    ## # A tibble: 5 × 19
    ##   line  stati…¹ stati…² stati…³ route1 route2 route3 route4 route5 route6 route7
    ##   <chr> <chr>     <dbl>   <dbl> <chr>  <chr>  <chr>  <chr>  <chr>  <chr>  <chr> 
    ## 1 6 Av… 7th Av     40.7   -74.0 F      <NA>   <NA>   <NA>   <NA>   <NA>   <NA>  
    ## 2 Brig… West 8…    40.6   -74.0 F      Q      <NA>   <NA>   <NA>   <NA>   <NA>  
    ## 3 Broa… Whiteh…    40.7   -74.0 R      1      <NA>   <NA>   <NA>   <NA>   <NA>  
    ## 4 Broa… South …    40.7   -74.0 R      1      <NA>   <NA>   <NA>   <NA>   <NA>  
    ## 5 Quee… Elmhur…    40.7   -73.9 M      R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ## # … with 8 more variables: route8 <dbl>, route9 <dbl>, route10 <dbl>,
    ## #   route11 <dbl>, entry <chr>, vending <chr>, entrance_type <chr>, ada <lgl>,
    ## #   and abbreviated variable names ¹​station_name, ²​station_latitude,
    ## #   ³​station_longitude

There are 465 dstinct stations. And 84 stations are ada compliant. There
are 9 stations that does not have vending machine, and 5 of them allows
entry. Therefore, 5/9 station entrances / exits without vending allow
entrance.
